### ISSUE TITLE
Android Support Repository

### ISSUE THREAD

**Issue by baoti** [inferjay/AndroidDevTools#12]
能添加 Extras/Android Support Repository 的下载地址吗? SDK Manager 中已经更新至 11 了.

**Comment by inferjay** [comment]
看这里https://github.com/inferjay/AndroidDevTools#support-library

**Comment by baoti** [comment]
Android Support Library 和 Android Support Repository 不是同一个。

Android Support Repository 里面包含 m2repository和support目录，为maven和gradle提供com.android.support依赖，比如像下面这样的：

    compile 'com.android.support:appcompat-v7:21.0.2'
    compile 'com.android.support:cardview-v7:21.0.2'
    compile 'com.android.support:recyclerview-v7:21.0.2'
    compile 'com.android.support:support-annotations:21.0.2'

    // 这两项要求 Android Support Repository 更新至 revision 11
    androidTestCompile('com.android.support.test:testing-support-lib:0.1')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.0')

另附文件build.gradle：
https://github.com/googlesamples/android-testing/blob/master/espresso/BasicSample/app/build.gradle#L31

**Comment by inferjay** [comment]
你将https://github.com/inferjay/AndroidDevTools#support-library或者https://github.com/inferjay/AndroidDevTools#android-sdk-extras下载下来解压开看看里面已经包含Support Repository(m2repository)

**Comment by baoti** [comment]
嗯，确实有m2repository，版本是Pkg.Revision=10.0.0。
最新版r11里面增加了com.android.support.test包。

**Comment by inferjay** [comment]
没有吧21.0.3我已经更新到最新的了，你是用什么系统的？

**Comment by inferjay** [comment]
我又重新更新了一下support-library和sdk-extras你看下

**Comment by baoti** [comment]
好了。不过建议把 m2repository 的版本号单独说明一下，不然不清楚要不要更新。

**Comment by inferjay** [comment]
OK，感谢提醒:)
