### ISSUE TITLE
是否可以考虑提供绿色版的 andriod studio

### ISSUE THREAD

**Issue by lionm117** [inferjay/AndroidDevTools#13]
安装使用谷歌的产品或许是最痛快的一件事事情，尤其是第一次做的时候， 基本所有的东西都被墙了。
为了安装 一个开发环境，结果发现国外提供所有基本方案，基本对天朝区都是无效。 浪费时间和精力不说， 还严重伤害积极性。 
由于被墙的原因，每在一台电脑上搭建一个开发环境都需要去连接被墙的网址下载资料，简直会让人发疯。 
使用安装包的方式仍然需要大量的配置之后，才可以正式开发， 感觉整个过程都比较繁琐， 做了两次之后就不想再干了。 
特提出一个好的方案：
是否可以提供一个绿色版的 开发工具 andriod studio ， 如果多台电脑需要配置， 只需要直接从 A 电脑拷贝B 电脑就一切OK ， 再也不用大量下载各种控件，各种SDK ，各种短时间都不用到的东西。

**Comment by inferjay** [comment]
这个之前也有想过依托Github来做更新，后来发现坑太深了，跳进去就出不来了，win 版的andriod studio不需要安装也可以用的吧，至于SDK什么的都已上传到网盘了,根据自己的需求下载相应的即可，不过最好还是准备个“梯子”，可以在线安装和更新。
