### ISSUE TITLE
android SDK 是否需要配套使用 ？ 

### ISSUE THREAD

**Issue by lionm117** [inferjay/AndroidDevTools#18]
#问题

> 鉴于android SDK 安装工具 是无法在国内直接在线更新的，(本通过 *镜像*的方式 和 *goagent 代理*的方式都失败)， 最后走了一条最笨的办法，逐个资源下载，解压释放使用。 但是android 存在多个 系统版本， 同时也存在多个版本的 **Support Library ，Build-Tools ，SDK Platform-Tools**之类的工具，最后**搞得 SDK 包极其庞大**。
但是在实际的开发过程中，会依赖的开发的系统可能就 那么一两个： android 5.0最新版， android 4.2 。  多个版本的工具和 SDK 维护起来也麻烦。

-------------------------

假如我只想搭建 一个**最简的开发环境基于 android 4.2 系统**（仅***开发，不需要测试环境）***

 > 哪些资源对于我是**必须的**，各个资源资源之间是否存在**版本配套**使用的问题？

**Comment by inferjay** [comment]
搭建 一个最简的开发环境基于 android 4.2 系统（仅开发，不需要测试环境）需要以下资源：
SDK Tools：http://www.androiddevtools.cn/#sdk-tools
SDK Platform-Tools：http://www.androiddevtools.cn/#sdk-platform-tools
Build-Tools：http://www.androiddevtools.cn/#build-tools
这3个是需要配套使用的,下载最新的就行了

SDK platforms：http://www.androiddevtools.cn/#sdk-list（只下载你需要的android 4.2即可 ）
SDK System images：http://www.androiddevtools.cn/#sdk-system-images
这两个也需要配套的，都下载4.2的

Android SDK Extras：http://www.androiddevtools.cn/#android-sdk-extras
这个不算必须的吧，要看项目需求吧，里面包含了很多，如果你要向下或者向上兼容会需要用到
