### ISSUE TITLE
网站访问不了

### ISSUE THREAD

**Issue by marcoszh** [inferjay/AndroidDevTools#22]
北京时间3.29上午八点半，我是一个人吗？？

**Comment by bylijian** [comment]
不是，3.29,11:00，也上不了

**Comment by inferjay** [comment]
时断时续的，我正在修复:)

**Comment by inferjay** [comment]
@marcoszh @bylijian 已经可以访问了，求帮忙测试下 :)

**Comment by bylijian** [comment]
可以了，之前出了什么问题么？

**Comment by inferjay** [comment]
网站是布在Github Page上的，这两天GFW盯上了Github，So...

**Comment by Gracker** [comment]
fuck the wall 发自网易邮箱大师 在2015年03月29日 15:56 ，HC ZHANG写道： 网站是布在Github Page上的，这两天GFW盯上了Github，So... — Reply to this email directly or view it on GitHub.

**Comment by marcoszh** [comment]
点赞，辛苦了

**Comment by inferjay** [comment]
:)
