### ISSUE TITLE
建议添加Android Killer

### ISSUE THREAD

**Issue by pwelyn** [inferjay/AndroidDevTools#26]
Android Killer 是一款可视化的安卓应用逆向工具，集Apk反编译、Apk打包、Apk签名，编码互转，ADB通信（应用安装-卸载-运行-设备文件管理）等特色功能于一 身，支持logcat日志输出，语法高亮，基于关键字（支持单行代码或多行代码段）项目内搜索，可自定义外部工具；吸收融汇多种工具功能与特点，打造一站 式逆向工具操作体验，大大简化了用户在安卓应用/游戏修改过程中的各类繁琐工作。
主要功能：

1、可视化、全自动的反编译、编译、签名；支持批量编译APK。

2、以树形目录管理反编译出的Apk源码文件，浏览、打开、编辑、都可以统一在软件中实现，不同项目间可以自由切换，方便快捷。

3、自动识别图像资源，并提供该类资源的快捷替换功能，方便修改这类图片资源。

4、内置代码编辑器，支持包含（但不限于）.samli、.xml、.html等各类格式文件的语法高亮显示，根据 smali文件格式的自动匹配相应语法；同时支持使用系统编辑器来编辑代码文件。

5、内置基于文件内容的单行或多行代码关键字搜索、可显示无穷多个搜索结果以标签的形式分门别类；可指定搜索范围（整个项目或在指定的文件或文件夹中搜索）、大小写，编码类型；从此无需再借助其他工具，即可轻松的完成搜索任务。

6、内嵌Unicode、UTF8、ANSI编码互转工具，方便硬编码文字的检索以及相关汉化类修改。

7、内置Log等调试工具，方便应用进程、logcat输出查看等进阶操作，监测修改apk的运行状况，以助于分析和查找错误

8、内置ADB功能，包括使用ADB向设备（或模拟器）安装、卸载、运行修改后的apk，进行测试，并可管理所连接设备的存储文件（包括系统以及用户文件）

9、所有操作步骤、结果都会显示在日志窗口，方便查看。

10、默认支持记事本、计算器等小工具，开放设置接口可根据本人需要自定义外部工具，满足个性化需求。

链接：http://www.pd521.com/thread-103-1-1.html

**Comment by inferjay** [comment]
感谢推荐，已添加:)

**Comment by changxiaokang** [comment]
:smiley: 啥时候更新调试功能哩，调试功能才是最想要的
