### ISSUE TITLE
求更新啊

### ISSUE THREAD

**Issue by chenenyu** [inferjay/AndroidDevTools#29]
sdk更新了好多版本  但是这里面都没有啊

**Comment by inferjay** [comment]
用中国科学院开源协会的Android SDK在线更新镜像服务器在线吧，速度嗷嗷的。

**Comment by ZSMJ2014** [comment]
中科院的镜像服务器很快的

**Comment by renfeng** [comment]
Hi chenenyu

你可以制作自己的镜像服务器（大概20GB），这里有方法
https://docs.google.com/presentation/d/1tEm-JweMHKUki4E14fteX9iZMXXqc-nIdrlq2Uow9lQ/edit

Frank

**Comment by inferjay** [comment]
周末搭一个试试:)

**Comment by renfeng** [comment]
现在可以支持将镜像作为 http proxy 来使用了
https://docs.google.com/presentation/d/1JnGpK3YJrMY-f3M0pq6RkyAu2p-wct6DCwCOacCDGO8/edit

**Comment by chenenyu** [comment]
thanks，i'll have a try 😄


在2015年05月21日 07:11，Frank R. 写道:

Hi chenenyu

你可以制作自己的镜像服务器（大概20GB），这里有方法
https://docs.google.com/presentation/d/1tEm-JweMHKUki4E14fteX9iZMXXqc-nIdrlq2Uow9lQ/edit

Frank

**Comment by inferjay** [comment]
赞👍，但是打开需要权限，已申请 :)

**Comment by sunpengshuai** [comment]
没有最新的哦～～
求更新～

**Comment by renfeng** [comment]
自己动手丰衣足食。

如何在局域网搭建 Android Repository 镜像
https://docs.google.com/presentation/d/1JnGpK3YJrMY-f3M0pq6RkyAu2p-wct6DCwCOacCDGO8/edit

完整的源代码在这里
https://github.com/renfeng/android-repository
