### ISSUE TITLE
Android Studio 1.3 下载 ndk

### ISSUE THREAD

**Issue by baoti** [inferjay/AndroidDevTools#35]
Android Studio 1.3 在 Settings > Appearance & Behavior > System Settings > Android SDK > SDK Tools中增加了 NDK 1.0.0
一直下载超时。

另外 Android Studio 的 HTTP Proxy 也设置不了。

**Comment by inferjay** [comment]
1.关于设置代理你可以参考下这个篇文章：http://www.licheedev.com/2015/06/22/gradle-proxy-for-as-1-3/
2.你可以去[这里](http://www.androiddevtools.cn/#ndk)下载，然后解压(Mac和Linux系统看[这里](https://github.com/inferjay/AndroidDevTools/wiki/Installing-the-NDK-On-Linux-and-Mac-OS-X-(Darwin))),再然后设置NDK的Location

**Comment by baoti** [comment]
Android NDK location 不可选择。
sdk 与 android-ndk-r10d 在同一级目录下，如何操作？

**Comment by inferjay** [comment]
@baoti 先打开一个项目，然后从
![5](https://cloud.githubusercontent.com/assets/1520409/9230889/aa763b2e-4157-11e5-8bae-12f15cf25f52.png)
或者
![6](https://cloud.githubusercontent.com/assets/1520409/9230826/20f238bc-4157-11e5-908d-0c7770c363b6.png)
打开Project Structure就可以设置NDK Location 了

**Comment by baoti** [comment]
![1](https://cloud.githubusercontent.com/assets/3110710/9244372/2a6ff3fe-41cd-11e5-977a-219e743700f0.jpg)

这里无法点击

**Comment by baoti** [comment]
从 Project Structure 进去后可以设置了。
