### ISSUE TITLE
腾讯镜像使用方法似乎不同？

### ISSUE THREAD

**Issue by JokerQyou** [inferjay/AndroidDevTools#37]
需要添加 User defined addon site 并且同时填写 proxy 地址才能使用，单独填写 proxy 的话下载是 503。

**Comment by JokerQyou** [comment]
详见 http://android-mirror.bugly.qq.com:8080/include/usage.html

**Comment by inferjay** [comment]
感谢提醒，我去把使用方法更新上去

**Comment by inferjay** [comment]
已添加
