### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by FinalLody** [inferjay/AndroidDevTools#40]
### 错误位置:
腾讯Bugly 镜像:

http://android-mirror.bugly.qq.com 端口：8080
### 应改为:
腾讯Bugly 镜像:

android-mirror.bugly.qq.com 端口：8080

### 添加http://前缀后这个镜像将无法使用.

**Comment by inferjay** [comment]
使用方法里有提示，在填写地址的时候不要加 'http://' ，我去把所有镜像地址的 'http://' 都去掉
