### ISSUE TITLE
使用方法里的已经不适用于Android2.0了啊

### ISSUE THREAD

**Issue by rabbit8ge** [inferjay/AndroidDevTools#41]
其中像代理设置都不一样了

**Comment by inferjay** [comment]
那个不适用了？

**Comment by junwangInChina** [comment]
对啊，2.1的，代理设置了，但是下载sdk还是报错，连不上。

**Comment by inferjay** [comment]
你肿么设置的，截个图我看下

**Comment by hojas** [comment]
![image](https://cloud.githubusercontent.com/assets/4729039/18302749/0ac00832-750c-11e6-97da-414c26c10710.png)

这样设置了也不行

**Comment by inferjay** [comment]
**使用方法**：
	
1. 启动 Android SDK Manager ，打开主界面，依次选择『**Tools**』、『**Options...**』，弹出『**Android SDK Manager - Settings**』窗口；

2. 在『**Android SDK Manager - Settings**』窗口中，在『**HTTP Proxy Server」和「HTTP Proxy Port**』输入框内填入上面镜像服务器地址(**不包含http://**，如下图)和端口，并且选中『**Force https://... sources to be fetched using http://...**』复选框。设置完成后单击『**Close**』按钮关闭『**Android SDK Manager - Settings**』窗口返回到主界面；

3. 依次选择『**Packages**』、『**Reload**』。

	<img src="https://raw.githubusercontent.com/inferjay/AndroidDevTools/master/static/image/sdk-manager-proxy-settings.png" width="40%" height="20%" alt="SDK Manager Proxy Settings">

**Comment by hojas** [comment]
我是在 Ubuntu 下安装的 Android studio 2.1.2

**Comment by inferjay** [comment]
那不用设置代理也不用镜像就可以更新了

**Comment by hojas** [comment]
不设置代理也不行。。。

**Comment by inferjay** [comment]
点击 “Lauch Standalone SDK Manager” 就可以打开 SDK Manager 了，然后就可以使用镜像地址了

**Comment by inferjay** [comment]
另外可以试试这个：https://dsx.bugly.qq.com

**Comment by hojas** [comment]
可以了，谢谢
