### ISSUE TITLE
你好，Eclipse下Sdk和adt的对应关系可以说下嘛？

### ISSUE THREAD

**Issue by JKAK47** [inferjay/AndroidDevTools#44]
我遇到的问题是在Ubuntu14.04 32bit机子上用eclipse新建一个空白project都会报错。就是R文件不能自动生成。报错说aapt找不到。但是我根据报错信息给出的路径是可以找到的。我也试过了网上提出的解决方案。主要有这几种。
1、aapt需要32bit支持库，如果Ubuntu是64bit的需要安装32bit的支持库。我的是32bit的
2、一种说法是后来的sdk把aapt工具放在了build-tools目录下。你需要在platform-tools目录下新建一个队build-tools目录中aapt文件的软连接。我也做了。
3、build-tools工具没有更新到最新。更新了
4、adt和sdk版本没有对应。这个是我要问你的问题。我安装的adt-23.0.4.zip版本。sdk呢API23最高。谢谢。

**Comment by inferjay** [comment]
1.建议你换 Android Studio 官方已经基本停止对 ADT 插件的维护了
2.安装adt-23.0.7.zip SDK 和 ADT 之间没有确切的对应关系，最新的ADT配最新的SDK
