### ISSUE TITLE
想问一下这个网站是做什么？AndroidDevTools有什么用？

### ISSUE THREAD

**Issue by boboIqiqi** [inferjay/AndroidDevTools#45]
@inferjay 
您好。

我理解这个仓库就是一个主页，随时发布一些下载Android相关开发工具的下载地址是吗？
请问这些地址是AndroidDevTools本身做的镜像吗？

另外AndroidDevTools主网站上面的代理，只有南洋理工的那个可以用，其他的国内高校的，都已经被封了吗？为什么我用SDK Manager设置该代理后下载，下载不下来。
http://www.androiddevtools.cn/
主站上，只有第一个可以用，其他都不行了？

**Comment by inferjay** [comment]
可以这么理解，是先有的这个 Repo，后来才有的 androiddevtools.cn 这个网站
