### ISSUE TITLE
网站上的资源似乎很久没更新了？

### ISSUE THREAD

**Issue by ChaosLeong** [inferjay/AndroidDevTools#52]
有计划继续更新吗？还是不打算继续维护了？

**Comment by inferjay** [comment]
有计划，已经又积攒了一批工具，等忙完这段时间会有一波更新，网站新版本也在计划中，敬请期待哦:)

**Comment by ChaosLeong** [comment]
期待~ 偶尔扶墙抽风 sdkmanager 下载不了的时候就跑这下载了 👍
